---
- name: remove group
  hosts: amazon-linux
  become: yes
  vars:
    mygroup: ejemplo1
  tasks:
    - name: delete group
      ansible.builtin.group:
        name: "{{ mygroup }}"
        state: absent
