---
- hosts: redhat
  become: yes
  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: naty
      state: present
      key: "{{ lookup('file', '/home/nivia/public_keys') }}"
