---
- name: playbook 
  hosts: localhost
  become: yes 
  tasks:
  - name: Add host with custom SSH port
    ansible.builtin.known_hosts:
      name: '[nivia]:2222'
      key: '[nivia]:2222 ssh-rsa ASDeararAIUHI324324' # some key gibberish
      path: /etc/ssh/ssh_known_hosts
      state: present
