---
- name: playbook 
  hosts: centos7
  become: yes 
  tasks:
  - name: Crear una nueva particion.
    parted:
      device: /dev/sdb
      number: 1
      state: present
      part_end: 3GiB

  - name: crear un volume group
    lvg:
       vg: mi_vg
       pvs: /dev/sdb1
       pesize: 16

  - name: crear un logical volume.
    lvol:
       vg: mi_vg
       lv:  mi.log.vol
       size: 1G
       force: yes

  - name: Crear un directorio si no existe
    file:
      path: /home/nivia/file_sys
      state: directory
      mode: '0755'

  - name: format the xfs filesystem.
    filesystem:
      fstype: xfs
      dev: /dev/mi_vg/mi.log.vol

  - name: montar.
    mount:
      path: /home/nivia/fi-sys
      src: /dev/mi_vg/mi.log.vol
      fstype: xfs
      state: mounted